version: 2.1
jobs:
  build:
    working_directory: ~/circleci-ruby-rails

    # Primary container image where all commands run

    docker:
      - image: circleci/ruby:3.0.2-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root

    # Service container image available at `host: localhost`

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-{{ checksum "Gemfile.lock" }}
            - rails-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle check || bundle install --jobs 4 --retry 3

      - run: sudo apt install -y postgresql-client || true

      # Store bundle cache
      - save_cache:
          key: rails-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:structure:load

      - run:
          name: Update chromedriver
          command: env RAILS_ENV=test bin/rails runner "Webdrivers::Chromedriver.update"

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Compile Webpacker
          command: |
            RAILS_ENV=test bundle exec rails webpacker:compile

      - run:
          name: Test
          command: bin/rails test:all

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results
